
<script type="text/javascript">
<?php echo $this->tinyMce(array(
	'mode' => 'exact',
	'elements' => 'base-text',
	'plugins' => "pagebreak,style,layer,table,emotions,inlinepopups,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,wordcount,advlist",
	'theme_advanced_buttons1' => "fontsizeselect,bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,outdent,indent,|,forecolor,backcolor,|,link,unlink,image,|,cut,copy,paste,pastetext,pasteword,|,undo,redo,|,cleanup,removeformat,code,fullscreen",
	'theme_advanced_buttons2' => "tablecontrols",
	'theme_advanced_buttons3' => null,
	'theme_advanced_buttons4' => null,
)) ?>

jQuery(function(){
});
</script>

<h1>Modifica Pagina</h2>
<?php echo $this->form ?>




