<script type="text/javascript">

<?php echo $this->tinyMce(array(
	'mode' => 'exact',
	'elements' => 'base-text',
	'plugins' => "pagebreak,style,layer,table,emotions,inlinepopups,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,wordcount,advlist",
	'theme_advanced_buttons1' => "fontsizeselect,bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,outdent,indent,|,forecolor,backcolor,|,link,unlink,image,|,cut,copy,paste,pastetext,pasteword,|,undo,redo,|,cleanup,removeformat,code,fullscreen",
	'theme_advanced_buttons2' => "tablecontrols",
	'theme_advanced_buttons3' => null,
	'theme_advanced_buttons4' => null,
)) ?>

</script>

	<h2><?php echo $this->translate('estate_admin_edit') ?></h2>
	<?php
		$this->headLink()->appendStylesheet('/pub/blueimp/jquery.fileupload-ui.css');
		$this->headLink()->appendStylesheet('/pub/jquery.fancybox-1.3.4/jquery.fancybox-1.3.4.css');
		$this->headScript()->appendFile('/pub/jquery.fancybox-1.3.4/jquery.fancybox-1.3.4.pack.js', 'text/javascript');
	?>

<?php
	$id_ad = $this->form->getValue('id');
	$add_files		= $this->translate('estate_add_files');
	$upload_start	= $this->translate('estate_start_upload');
	$upload_cancel	= $this->translate('estate_cancel_upload');
	$upload_delete	= $this->translate('estate_delete_selected');
	$next			= $this->translate('estate_next');
	$previous		= $this->translate('estate_previous');
	$download		= $this->translate('estate_download');
	echo $this->form;
?>
	<div class="row-fluid">
		<div class="well span12">
			<form id="fileupload" action="/estate/admin/blueimp/id/<?php echo $id_ad ?>" method="POST" enctype="multipart/form-data" class="">
				<div class="row-fluid">
					<div class="span12 fileupload-buttonbar">
						<div class="progressbar fileupload-progressbar fade"><div style="width:0%;"></div></div>
						<span class="btn btn-success fileinput-button">
							<span><?php echo $add_files ?></span>
							<input type="file" name="files[]" multiple>
						</span>
						<button type="submit" class="btn btn-primary start"><?php echo $upload_start ?></button>
						<button type="reset" class="btn btn-info cancel"><?php echo $upload_cancel ?></button>
						<button type="button" class="btn btn-danger delete"><?php echo $upload_delete ?></button>
						<input type="checkbox" class="toggle">
					</div>
				</div>
				<br /><br />
				<div class="row-fluid">
					<table class="table-striped span12">
						<colgroup>
							<col style="width: 90px;" />
							<col style="width: 60%;" />
						</colgroup>
						<tbody class="files"></tbody>
					</table>
				</div>
			</form>
		</div>
	</div>

	<div class="modal hide fade" id="myModal">
		<div class="modal-header">
			<a href="javascript:void(0);" class="close" data-dismiss="modal">×</a>
			<h3><?php echo $this->translate('estate_modal_preview') ?></h3>
		</div>
		<div class="modal-body">
			<img id="preview" src="" style="width: 320px; height: 240px; margin: 0pt auto; display: block;" />
		</div>
		<div class="modal-footer">
			<a href="javascript:void(0);" class="btn" data-dismiss="modal">Close</a>
		</div>
	</div>

<script>
var fileUploadErrors = {
	maxFileSize: '<?php echo $this->translate('estate_maxFileSize') ?>',
	minFileSize: '<?php echo $this->translate('estate_minFileSize') ?>',
	acceptFileTypes: '<?php echo $this->translate('estate_acceptFileTypes') ?>',
	maxNumberOfFiles: '<?php echo $this->translate('estate_maxNumberOfFiles') ?>',
	uploadedBytes: '<?php echo $this->translate('estate_uploadedBytes') ?>',
	emptyResult: '<?php echo $this->translate('estate_emptyResult') ?>'
};
</script>
<script id="template-upload" type="text/html">
{% for (var i=0, files=o.files, l=files.length, file=files[0]; i<l; file=files[++i]) { %}
	<tr class="template-upload fade">
		<td class="preview"><span class="fade"></span></td>
		<td class="name">{%=file.name%}</td>
		<td class="size" style="width: 75px;">{%=o.formatFileSize(file.size)%}</td>
		{% if (file.error) { %}
			<td class="error" colspan="2"><span class="label important"><?php echo $this->translate('estate_error') ?></span> {%=fileUploadErrors[file.error] || file.error%}</td>
		{% } else if (o.files.valid && !i) { %}
			<td class="progress"><div class="progressbar"><div style="width:0%;"></div></div></td>
			<td class="start">{% if (!o.options.autoUpload) { %}<button class="btn btn-primary"><?php echo $this->translate('estate_start') ?></button>{% } %}</td>
		{% } else { %}
			<td colspan="2"></td>
		{% } %}
		<td class="cancel" style="width: 120px;">{% if (!i) { %}<button class="btn btn-info"><?php echo $this->translate('estate_cancel') ?></button>{% } %}</td>
	</tr>
{% } %}
</script>
<script id="template-download" type="text/html">
{% for (var i=0, files=o.files, l=files.length, file=files[0]; i<l; file=files[++i]) { %}
	<tr class="template-download fade">
		{% if (file.error) { %}
			<td></td>
			<td class="name">{%=file.name%}</td>
			<td class="size" style="width: 75px;">{%=o.formatFileSize(file.size)%}</td>
			<td class="error" colspan="2"><span class="label important"><?php echo $this->translate('estate_error') ?></span> {%=fileUploadErrors[file.error] || file.error%}</td>
		{% } else { %}
			<td class="preview">{% if (file.thumbnail_url) { %}
				<a href="javascript:show_modal('{%=file.url%}');" title="{%=file.name%}" rel="gallery"><img src="{%=file.thumbnail_url%}"></a>
			{% } %}</td>
			<td class="name">
				<a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" target="_blank">{%=file.name%}</a>
			</td>
			<td class="size" style="width: 75px;">{%=o.formatFileSize(file.size)%}</td>
			<td colspan="2"></td>
		{% } %}
		<td class="delete" style="width: 120px;">
			<button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}"><?php echo $this->translate('estate_delete') ?></button>
			<input type="checkbox" name="delete" value="1">
		</td>
	</tr>
{% } %}
</script>


<!-- The Templates and Load Image plugins are included for the FileUpload user interface -->
<script src="/pub/blueimp/tmpl.min.js"></script>
<script src="/pub/blueimp/load-image.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/pub/blueimp/jquery.iframe-transport.js"></script>
<script src="/pub/blueimp/jquery.fileupload.js"></script>
<script src="/pub/blueimp/jquery.fileupload-ui.js"></script>
<script src="/pub/blueimp/application.js"></script>
<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE8+ -->
<!--[if gte IE 8]><script src="/pub/blueimp/cors/jquery.xdr-transport.js"></script><![endif]-->


