<?php
	$this->headLink()->appendStylesheet('/pub/jquery.fancybox-1.3.4/jquery.fancybox-1.3.4.css');
	$this->headScript()->appendFile('/pub/jquery.fancybox-1.3.4/jquery.fancybox-1.3.4.pack.js', 'text/javascript');
?>
<script type="text/javascript">
<!--
jQuery(function(){
	jQuery('#ad_gallery a').fancybox({});
});
//-->
</script>

<div id="estate_ad" class="row-fluid">
	<div class="span12">
		<h1><?php echo $this->data['title'] ?></h1>
		<p class="ad_date">Data annuncio: <?php echo preg_replace('/^([0-9]{4})-([0-9]{2})-([0-9]{2}).*$/', '$3/$2/$1', $this->data['date']) ?></p>
	</div>
	<div class="span12">
		<div class="row-fluid">
			<div class="span6">
				<?php
					$clean_title = str_replace('"', '', $this->data['title']);
					$img_width = 300;
					$img_heigh = (int) ceil($img_width * 0.75);
					$img_src = "/file/media/{$this->data['primary_image-id']}/$img_width/$img_heigh?name={$this->data['primary_image-name']}&sum={$this->data['primary_image-md5']}";
					echo "<img class=\"ad_primary\" src=\"$img_src\" width=\"$img_width\" height=\"$img_heigh\" alt=\"$clean_title\"/>";
				?>
				<div id="ad_gallery">
					<?php
						$_basepath = realpath(Zend_Registry::get('config')->file->path->storage);
						$_relpath = "/estate/gallery/{$this->data['id']}/";
						$_path = $_basepath.$_relpath;
						if (file_exists($_path)) :
							$_list = new FilesystemIterator($_path, FilesystemIterator::CURRENT_AS_FILEINFO);
							/* @var $file SplFileInfo */
							foreach ($_list as $file):
								if (!$file->isFile()) continue;
								$img_width = 40;
								$img_heigh = (int) ceil($img_width * 0.75);
								$imgpath = $_relpath.$file->getBasename();
							?>
								<a href="<?php echo $this->url(array('w'=>1920, 'h'=>1080, 'path'=>$imgpath), 'image', true, false) ?>" rel="gallery">
									<img alt="Immagine" src="<?php echo $this->url(array('w'=>$img_width, 'h'=>$img_heigh, 'path'=>$imgpath), 'thumb', true, false) ?>" />
								</a>
							<?php
							endforeach;
						?>
					<?php endif;?>
				</div>
				<table class="table table-condensed">
					<tbody>
					<?php
						foreach ($this->data as $k => $v):
							switch ($k):
								case 'province':
								case 'district':
								case 'address':
								case 'metrics':
								case 'type':
								case 'category':
								case 'kind':
								case 'rooms':
								case 'bathrooms':
								case 'balcony':
								case 'heating':
								case 'elevator':
								case 'parking':
								case 'garage':
								case 'floor':
								case 'floors':
								case 'state':
								case 'build_year':
								case 'monthly_charge':
								case 'deed':
								case 'price':

								case 'giardino': // !!!!!!!!!!!!!!!!!!
								case 'trattabile':// ??????????????????
								case 'disponibilità': // !!!!!!!!!!!!!!!!!!!!!
								case 'livelli interni':// ????????????????
								case 'enti':// ???????????????????
								case 'cantina': // DA IMPLEMENTARE ????
									if (empty($v) OR $v === '--') continue;
							?>
								<tr>
									<td><strong><?php echo $this->translate('estate_'.$k) ?></strong>:</td>
									<td><?php echo $v ?></td>
								</tr>
							<?php
								break;
							endswitch;
						endforeach;
					?>
					</tbody>
				</table>
			</div>
			<div class="span6">
				<div class="ad_text"><?php echo $this->data['text'] ?></div>
				<?php if (!empty($this->data['price'])): ?>
				<p class="ad_price">Prezzo: &euro; <?php echo $this->data['price'] ?></p>
				<?php endif;?>
				<?php if (!empty($this->data['ad_code'])): ?>
				<p class="ad_code">Codice annuncio: <?php echo $this->data['ad_code'] ?></p>
				<?php endif;?>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12">
				<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=<?php echo 'AIzaSyDL7ObkkF6sMEG3SwyVvJlsGuqpAzCIkXg' ?>&sensor=false"></script>
				<script type="text/javascript">
					jQuery(function () {
						deim_gmap.init();
					});

					deim_gmap = {
						"_map": null,
						"init": function() {
							var options = {
								center: new google.maps.LatLng(0, 0),
								zoom: 12,
								mapTypeId: google.maps.MapTypeId.ROADMAP
							};
							deim_gmap._map = new google.maps.Map(document.getElementById("gmap_map"), options);
							deim_geocoder.init();
							deim_geocoder.gotoAddress("<?php echo $this->data['address'] ?>");
						},
						"getMap": function (){
							return deim_gmap._map;
						}
					};

					deim_geocoder = {
						"_geocoder": null,
						"_map": null,
						"init": function(){
							deim_geocoder._geocoder = new google.maps.Geocoder();
						},
						"gotoAddress": function (address) {
							deim_geocoder._geocoder.geocode({"address": address, "region": "<?php echo empty($this->data['state']) OR $this->data['state'] === '--' ? 'it' : $this->data['state'] ?>"}, function(results, status){
								if (status == google.maps.GeocoderStatus.OK) {
									deim_gmap.getMap().setCenter(results[0].geometry.location);
									var marker = new google.maps.Marker({
										map: deim_gmap.getMap(),
										position: results[0].geometry.location
									});
								} else {
									deim_gmap = undefined;
									jQuery('#gmap_map').remove();
								}
							});
						}
					};
				</script>
				<?php $this->headStyle()->captureStart() ?>
					#gmap_map img {
						max-width: none;
					}
				<?php $this->headStyle()->captureEnd() ?>
				<div id="gmap_map" style="height: 450px; width: 600px;"></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12">
				<?php echo $this->requestform ?>
			</div>
		</div>
	</div>
</div>
























