
<script type="text/javascript">
<!--
jQuery(function(){
	jQuery('.estate_ad:odd').addClass('odd');
	jQuery('.estate_ad:even').addClass('even');
});
//-->
</script>

<?php echo new estate_forms_AdvancedSearch() ?>
<h1>Elenco annunci</h1>
<?php
	$clear = 1;
	foreach ($this->list as $ad)
		echo $this->partial('estate/views/partials/ad/list_element.phtml', $ad);
?>

<?php echo $this->paginationControl($this->list, 'Sliding', 'estate/views/partials/ad/paginator.phtml'); ?>