

function apeFilemanager_browser_callback (field_name, url, type, win, callback)
{
	/**
	 * alert("Field_Name: " + field_name + "\nURL: " + url + "\nType: " + type + "\nWin: " + win);
	 * Field_Name: src
	 * URL: /ciao
	 * Type: image
	 * Win: [object Window]
	 */
	var cmsURL = "/file/manager/list";

	if (cmsURL.indexOf("?") < 0) {
		//add the type as the only query parameter
		cmsURL = cmsURL + "?type=" + type;
	} else {
		//add the type as an additional query parameter
		// (PHP session ID is now included if there is one at all)
		cmsURL = cmsURL + "&type=" + type;
	}
	if (url.length > 0)
		cmsURL = cmsURL + "&folder=" + url.replace('/file/index/get/?path=', '');

	tinyMCE.activeEditor.windowManager.open({
		file : cmsURL,
		title : "File Browser",
		width : 640,
		height : 480,
		resizable : "yes",
		inline : "yes",  // This parameter only has an effect if you use the inlinepopups plugin!
		close_previous : "no"
	}, {
		window : win,
		input : field_name
	});
	callback.call();
	return false;
}
