
<script type="text/javascript">

<?php echo $this->tinyMce(array(
	'mode' => 'exact',
	'elements' => 'application[website_sidebox]',
	'plugins' => "pagebreak,style,layer,table,emotions,inlinepopups,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,wordcount,advlist",
	'theme_advanced_buttons1' => "fontsizeselect,bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,outdent,indent,|,forecolor,backcolor,|,link,unlink,image,|,cut,copy,paste,pastetext,pasteword,|,undo,redo,|,cleanup,removeformat,code,fullscreen",
	'theme_advanced_buttons2' => "tablecontrols",
	'theme_advanced_buttons3' => null,
	'theme_advanced_buttons4' => null,
)) ?>

</script>

<h2>Configurazione</h2>
<?php echo $this->form ?>



<?php $this->placeholder('sidebox-menu')->captureStart() ?>

<div class="well sidebar-nav">
	<ul class="nav nav-list">
		<li class="nav-header">Avanzate</li>
		<?php /*
		<li>
			<a title="Modifica Layout" href="/theme/admin/index"><i class="icon-home"></i> Theme manager</a>
		</li>
		*/?>
		<li>
			<a title="Gestione file" href="/theme/admin/media"><i class="icon-picture"></i> Media manager</a>
		</li>
	</ul>
</div>

<?php $this->placeholder('sidebox-menu')->captureEnd() ?>